ads-feature:
  root-uri: http://localhost:9090
  request_url: /fun7-ad-partner?countryCode={cc}
  user_name: fun7user
  user_pass: fun7pass
  enabled_str: "sure, why not!"

resilience4j:
  circuitbreaker:
    instances:
      externalApiCB:
        base-config: shared
    configs:
      shared:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 40
        slow-call-rate-threshold: 40
        permitted-number-of-calls-in-half-open-state: 1
        max-wait-duration-in-half-open-state: 10s
        wait-duration-in-open-state: 10s
        slow-call-duration-threshold: 2s
        writable-stack-trace-enabled: true
        automatic-transition-from-open-to-half-open-enabled: true
