ads-feature:
  root-uri: http://localhost:9090
  request_url: /fun7-ad-partner?countryCode={cc}
  user_name: fun7user
  user_pass: fun7pass
  enabled_str: "sure, why not!"

resilience4j:
  circuitbreaker:
    instances:
      externalApiCB:
        slidingWindowType: COUNT_BASED